stages:
  - build
  - test

image: python:3.8-slim-buster
before_script:
    - pip install -r requirements.txt
    - pip install dist/treevolution-0.0.1-py3-none-any.whl
build:
  stage: build
  script:
    - python -m build
    
test:
  stage: test
  script:
    - pytest --cov=src/treevolution 

