stages:
  - build
  - test

image: python:3.8-slim-buster
before_script:
    -pip install -e .
    - pip install -r requirements.txt
build:
  stage: build
  script:
    - python -m build
    
test:
  stage: test
  script:
    - pytest --cov=src/treevolution 

