stages:
  - build
  - test
  - deploy
  - deploy_heroku

image: python:3.8-slim-buster
before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install treevolution-0.0.5-py3-none-any.whl

build:
  stage: build
  script:
    - python -m build    

test:
  stage: test
  script:
    - pytest --cov=src/treevolution

pages:
  stage: deploy
  script:
   - sphinx-build -b html docs/source/  public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

heroku_deploy_dev:
  stage: deploy_heroku
  image: ruby:latest
  rules:
    - if: $CI_COMMIT_TAG
  when: never
    - when: always
  before_script:
    - echo "Prepare to deploy on Heroku on dev server"
  script:
    - gem install dpl dpl-heroku
    - dpl --provider=heroku --app=treevolution-etudiant-zelasri --api-key=$HEROKU_KEY
