stages:
  - build
  - test

image: python:3.8-slim-buster
before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -e .
build:
  stage: build
  script:
    - python -m build    
test:
  stage: test
  script:
    - pytest --cov=src/treevolution 

