stages:
  - build

image: python:3.8-slim-buster

build:
  stage: build
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m build
    
test:
  script:
    - pytest --cov=src/treevolution 

