[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "treevolution"
version = "0.0.1"
authors = [
  { name="Prénom Nom", email="prenom.nom@etu.univ-littoral.fr" },
]
description = "Tree simulator engine"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]